Add Integration Recipes (#388)
* wip

* feat: add GT material methods for MatterTransformerRecipeBuilder

* feat: more clear Error if defaultPrefix is null

* feat: Blast Furnace GT Recipes

* fix: shadowing

* feat: new GT recipes, don't disperse EIO recipe registration

* add default prefix ingot/dust for alloy recipes

* style: rm unused things

* feat: GT CA Injector recipes

* wip: ExR integration

* fix: ModId of ExtremeReactors

* feat: ExtremeReactors Recieps

* feat: TofuCraft

* feat: Early load Narrator mixin

* feat: tofu craft reload integration recipes

* feat: update README

* feat: add sakura mod as dependencies

* feat: Sakura mod recipes

* feat: Mekanism recipes

* feat: Omit spaces from ConfigModIntegration

* feat: TConstruct Recipes

* move AE2 Integration recipe registration to dedicated object

* feat: misc integration recipes

* feat: Thermal Integration recipes

* feat: Use simpler method

* feat: Project Red Integration recipes

* feat: properly merge

* feat: Coremod class should be a java class

* fix: Not loading as a noramal Mod

* fix: NoClassDefFoundError due to the typealiases

* fix: ProjectRedEx recipes

* feat: move mod deps to mod_dependencies.gradle

* feat: Galacticraft Integration Recipes

* feat: Misc Integration

* feat: metallurgy integration recipes

* feat: mv integration recipes to dedicated subpackage

* feat: cleanup

* feat: add global switch for integration recipes

* feat: Config Comments missing

* feat(wiki): dockerize

* feat: cargo make

* fix: mathjax3 5+ errors with `Tags with side effect ...`. downgrade to 4.3.2

* fix: ExR recipes

* fix: CA Injector GT Integration recipes is not loaded

* style

* feat: wiki

* feat: more compat recipes

* another integration recipe

* feat: more crop recipes

* feat: recipe config options

* feat: mv config, change packaging, add config wiki

* fix: docs

* feat: rm recipeStaticity option

* feat: more integration recipe and doc

* update README

* typo